export const COMPANY = {
  name: "Brisbane Grease Traps",
  phone: "0459 410 785",
  contactName: "Our team",
  email: "info@brisbanegreastraps.com.au",
  abn: "00 000 000 000",
  address: "Brisbane, Queensland, Australia",
  whatsapp: "61459410785",
};

export const NAV_LINKS = [
  { label: "About", href: "/about" },
  { label: "Industries", href: "/industries" },
  { label: "Services", href: "/services" },
  { label: "Contact", href: "/contact" },
];

export const SERVICE_AREAS = [
  "Brisbane CBD",
  "Fortitude Valley",
  "South Bank",
  "West End",
  "Newstead",
  "Teneriffe",
  "New Farm",
  "Woolloongabba",
  "Paddington",
  "Milton",
  "Toowong",
  "St Lucia",
  "Indooroopilly",
  "Chermside",
  "Nundah",
  "Lutwyche",
  "Clayfield",
  "Hamilton",
  "Ascot",
  "Eagle Farm",
  "Hendra",
  "Bowen Hills",
  "Albion",
  "Windsor",
  "Petrie Terrace",
  "Spring Hill",
  "Kelvin Grove",
  "Red Hill",
  "Auchenflower",
  "Taringa",
  "Kenmore",
  "The Gap",
  "Stafford",
  "Everton Park",
  "Mitchelton",
  "Keperra",
  "Ferny Grove",
  "Carindale",
  "Coorparoo",
  "Camp Hill",
  "Greenslopes",
  "Annerley",
  "Yeronga",
  "Moorooka",
  "Rocklea",
  "Sherwood",
  "Graceville",
  "Corinda",
  "Oxley",
  "Inala",
  "Forest Lake",
  "Richlands",
  "Darra",
  "Wacol",
  "Sumner",
  "Acacia Ridge",
  "Coopers Plains",
  "Sunnybank",
  "Sunnybank Hills",
  "Runcorn",
  "Calamvale",
  "Parkinson",
  "Algester",
  "Robertson",
  "Eight Mile Plains",
  "Upper Mount Gravatt",
  "Mount Gravatt",
  "Macgregor",
  "Holland Park",
  "Mansfield",
  "Wishart",
  "Stretton",
  "Drewvale",
  "Berrinba",
  "Kuraby",
];
